# -*- coding: utf-8 -*-
"""배경소음제거.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uyut4gW1e5FxnQyx2O-S9e4KXIb85bOj
"""

import numpy as np
import librosa
import matplotlib.pyplot as plt
from IPython.display import Audio, display

def remove_noise(audio_file):
    y, sr = librosa.load(audio_file)

    D = librosa.stft(y)

    magnitude, phase = librosa.magphase(D)

    mean_mag = np.mean(magnitude, axis=1)

    clean_magnitude = magnitude - mean_mag[:, np.newaxis]

    clean_magnitude = np.maximum(clean_magnitude, 0)

    clean_D = clean_magnitude * phase
    clean_y = librosa.istft(clean_D)

    return clean_y, sr

audio_file = '/content/drive/MyDrive/MFCC/cleaned/TEST_02195clean_clean.wav'

clean_audio, sr = remove_noise(audio_file)

plt.figure(figsize=(12, 6))

plt.subplot(2, 1, 1)
plt.title('Original Audio')
y, sr = librosa.load(audio_file)
plt.plot(np.arange(len(y)) / sr, y)
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')

plt.subplot(2, 1, 2)
plt.title('Cleaned Audio')
plt.plot(np.arange(len(clean_audio)) / sr, clean_audio)
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')

plt.tight_layout()
plt.show()

display(Audio(clean_audio, rate=sr))